spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_FORMAT_SQL}
        jdbc:
          batch_size: ${JPA_BATCH_SIZE}
          time_zone: ${JPA_TZ}
        order_inserts: true
        order_updates: true
      show-sql: ${JPA_SHOW_SQL}
      open-in-view: false

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}
    path: ${SWAGGER_PATH}
    tags-sorter: ${SWAGGER_TAGS_SORTER}
    operations-sorter: ${SWAGGER_OPER_SORTER}
  api-docs:
    enabled: ${SWAGGER_API_ENABLED}
    path: ${SWAGGER_API_PATH}